version: 0.5.1
output_dir: .
device_type: cuda
n_iterations: 2
memory: false
parameterisation_settings:
    smiles:
    - C
    initial_force_field: openff_unconstrained-2.3.0.offxml
    expand_torsions: true
    linearise_harmonics: true
    msm_settings:
        ml_potential: aceff-2.0
        finite_step: 0.0005291772 nm
        tolerance: 0.005291772 kcal * mol**-1 * A**-1
        vib_scaling: 0.958
        n_conformers: 1
    type_generation_settings:
        Bonds:
            max_extend_distance: -1
            include: []
            exclude: []
        Angles:
            max_extend_distance: -1
            include: []
            exclude: []
        ProperTorsions:
            max_extend_distance: -1
            include: []
            exclude:
            - '[*:1]-[*:2]#[*:3]-[*:4]'
            - '[*:1]~[*:2]-[*:3]#[*:4]'
            - '[*:1]~[*:2]=[#6,#7,#16,#15;X2:3]=[*:4]'
        ImproperTorsions:
            max_extend_distance: -1
            include: []
            exclude: []
training_sampling_settings:
    sampling_protocol: mm_md_metadynamics
    ml_potential: aceff-2.0
    timestep: 1 fs
    temperature: 500 K
    snapshot_interval: 0.16 ps
    n_conformers: 10
    equilibration_sampling_time_per_conformer: 0.0 ps
    production_sampling_time_per_conformer: 100 ps
    loss_energy_weight: 1000.0
    loss_force_weight: 0.1
    bias_width: 0.3141592653589793
    bias_factor: 20.0
    bias_height: 1.0 kJ * mol**-1
    bias_frequency: 0.1 ps
    bias_save_frequency: 10 ps
    torsions_to_include_smarts:
    - '[!#1:1]~[!$(*#*)&!D1:2]-!@[!$(*#*)&!D1:3]~[!#1:4]'
    - '[!#1:1]~[!$(*#*)&!D1&r5&!a:2]-@[!$(*#*)&!D1&r5&!a:3]~[!#1:4]'
    - '[!#1:1]~[!$(*#*)&!D1&r6&!a:2]-@[!$(*#*)&!D1&r6&!a:3]~[!#1:4]'
    - '[!#1:1]~[!$(*#*)&!D1&r7&!a:2]-@[!$(*#*)&!D1&r7&!a:3]~[!#1:4]'
    torsions_to_exclude_smarts: []
testing_sampling_settings:
    sampling_protocol: ml_md
    ml_potential: aceff-2.0
    timestep: 1 fs
    temperature: 298 K
    snapshot_interval: 20 fs
    n_conformers: 10
    equilibration_sampling_time_per_conformer: 0.0 ps
    production_sampling_time_per_conformer: 2 ps
    loss_energy_weight: 1000.0
    loss_force_weight: 0.1
training_settings:
    optimiser: adam
    parameter_configs:
        LinearBonds:
            cols:
            - k1
            - k2
            scales:
                k1: 0.0028
                k2: 0.0028
            limits:
                k1:
                - 1.0e-08
                - null
                k2:
                - 1.0e-08
                - null
            regularize: {}
            include: null
            exclude: null
        LinearAngles:
            cols:
            - k1
            - k2
            scales:
                k1: 0.012
                k2: 0.011
            limits:
                k1:
                - 1.0e-08
                - null
                k2:
                - 1.0e-08
                - null
            regularize: {}
            include: null
            exclude: null
        ProperTorsions:
            cols:
            - k
            scales:
                k: 1.3
            limits:
                k:
                - null
                - null
            regularize:
                k: 1.0
            include: null
            exclude:
            -   id: '[*:1]-[*:2]#[*:3]-[*:4]'
                mult: 0
                associated_handler: ProperTorsions
                bond_order: null
            -   id: '[*:1]~[*:2]-[*:3]#[*:4]'
                mult: 0
                associated_handler: ProperTorsions
                bond_order: null
            -   id: '[*:1]~[*:2]=[#6,#7,#16,#15;X2:3]=[*:4]'
                mult: 0
                associated_handler: ProperTorsions
                bond_order: null
        ImproperTorsions:
            cols:
            - k
            scales:
                k: 0.12
            limits:
                k:
                - 0.0
                - null
            regularize:
                k: 1.0
            include: null
            exclude: null
    attribute_configs: {}
    n_epochs: 1000
    learning_rate: 0.01
    learning_rate_decay: 1.0
    learning_rate_decay_step: 10
    regularisation_target: initial
outlier_filter_settings:
    energy_outlier_threshold: 2.0
    force_outlier_threshold: 500.0
    min_conformations: 1
